aliases:
  - &restore_cache
    keys:
      - dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - dependency-cache-{{ .Branch }}-
  - &save_cache
    key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
  - &store_report_artifacts
    destination: reports
    path: reports
  - &store_test_results
    path: reports/junit

version: 2.1
executors:
  node-10:
    docker:
      - image: circleci/node:10.15.1
  node-11:
    docker:
      - image: circleci/node:11.9.0
jobs:
  static-analysis:
    executor: node-10
    working_directory: ~/andrewjtorr.es
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn --no-progress
      - save_cache: *save_cache
      - run: mkdir --parents reports/junit
      - run: yarn --silent lint-scripts --format junit --output-file reports/junit/lint-scripts-results.xml
      - run: yarn --silent lint-styles --custom-formatter node_modules/stylelint-junit-formatter > reports/junit/lint-styles-results.xml
      - run: yarn --silent lint-types
      - store_artifacts: *store_report_artifacts
      - store_test_results: *store_test_results
  test-node-10:
    executor: node-10
    working_directory: ~/andrewjtorr.es
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn --no-progress
      - save_cache: *save_cache
      - run: mkdir --parents reports/junit
      - run:
          command: yarn --silent test-units --coverage --runInBand --reporters default jest-junit
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/unit-test-results.xml
      - run: yarn --silent codecov
      - store_artifacts: *store_report_artifacts
      - store_artifacts:
          destination: coverage
          path: coverage
      - store_test_results: *store_test_results
  test-node-11:
    executor: node-11
    working_directory: ~/andrewjtorr.es
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn --no-progress
      - save_cache: *save_cache
      - run: mkdir --parents reports/junit
      - run:
          command: yarn --silent test-units --runInBand --reporters default jest-junit
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/unit-test-results.xml
      - store_artifacts: *store_report_artifacts
      - store_test_results: *store_test_results
  release:
    environment:
      GIT_AUTHOR_EMAIL: andrew.jonathan.torres@gmail.com
      GIT_AUTHOR_NAME: Andrew Torres
      GIT_COMMITTER_EMAIL: andrew.jonathan.torres@gmail.com
      GIT_COMMITTER_NAME: Andrew Torres
    executor: node-10
    working_directory: ~/andrewjtorr.es
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn --no-progress
      - save_cache: *save_cache
      - add_ssh_keys:
          fingerprints:
            - 6c:49:0a:f4:da:57:85:87:1a:8b:32:f1:47:1a:d4:ed
      - run: yarn --silent semantic-release
workflows:
  version: 2.1
  test-and-release:
    jobs:
      - static-analysis
      - test-node-10
      - test-node-11
      - release:
          context: organization
          requires:
            - static-analysis
            - test-node-10
            - test-node-11
          filters:
            branches:
              only: master
